version: '2.3'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: denden047/machina:latest
    runtime: nvidia
    volumes:
      - type: bind
        source: ../src
        target: /workdir
    working_dir: /workdir
    command: python main.py
